// <auto-generated />
using System;
using GlobalTradeSevkiyatTakip.Persistance.EFContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GlobalTradeSevkiyatTakip.Persistance.Migrations
{
    [DbContext(typeof(EFDatabaseContext))]
    partial class EFDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GlobalTradeSevkiyatTakip.Domain.Entities.Cari", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Ad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Adres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CariKodu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("GuncellemeTarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("GuncelleyenKullanici")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Iletisim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("OlusturanKullanici")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OlusturmaTarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("Soyad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TcNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TicariUnvan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VergiDairesi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VergiNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("WolvoxBlKodu")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.ToTable("Cari");
                });

            modelBuilder.Entity("GlobalTradeSevkiyatTakip.Domain.Entities.Depo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("DepoAd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DepoAdres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DepoIletisim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DepoYetkili")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("GuncellemeTarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("GuncelleyenKullanici")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("OlusturanKullanici")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OlusturmaTarih")
                        .HasColumnType("datetime2");

                    b.Property<long?>("WolvoxBlKodu")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.ToTable("Depo");
                });

            modelBuilder.Entity("GlobalTradeSevkiyatTakip.Domain.Entities.DepoDetay", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Adet")
                        .HasColumnType("int");

                    b.Property<int?>("CariId")
                        .HasColumnType("int");

                    b.Property<int?>("DepoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("GuncellemeTarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("GuncelleyenKullanici")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("OlusturanKullanici")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OlusturmaTarih")
                        .HasColumnType("datetime2");

                    b.Property<int?>("StokId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TarihSaat")
                        .HasColumnType("datetime2");

                    b.Property<long?>("WolvoxBlKodu")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("CariId");

                    b.HasIndex("DepoId");

                    b.HasIndex("StokId");

                    b.ToTable("DepoDetay");
                });

            modelBuilder.Entity("GlobalTradeSevkiyatTakip.Domain.Entities.Doviz", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal?>("AlisFiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DovizBirim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("GuncellemeTarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("GuncelleyenKullanici")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("OlusturanKullanici")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OlusturmaTarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("OzelKod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("SatisFiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<long?>("WolvoxBlKodu")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.ToTable("Doviz");
                });

            modelBuilder.Entity("GlobalTradeSevkiyatTakip.Domain.Entities.Entegre", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("BeniHatirla")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("GuncellemeTarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("GuncelleyenKullanici")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("OlusturanKullanici")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OlusturmaTarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("Parola")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("EntegreKullanici");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            BeniHatirla = false,
                            Email = "entegre@gmail.com",
                            GuncellemeTarih = new DateTime(2023, 9, 8, 16, 13, 54, 99, DateTimeKind.Local).AddTicks(2935),
                            GuncelleyenKullanici = "asd",
                            IsDeleted = false,
                            OlusturanKullanici = "sd",
                            OlusturmaTarih = new DateTime(2023, 9, 8, 16, 13, 54, 99, DateTimeKind.Local).AddTicks(2935),
                            Parola = "jyBAdWogYwoYrNvTdwxwLKavHQiYqszX7dUAggFIfZhdDQFBvLfU1q3UMnCe1yVo",
                            Rol = 3
                        });
                });

            modelBuilder.Entity("GlobalTradeSevkiyatTakip.Domain.Entities.Fatura", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("CariId")
                        .HasColumnType("int");

                    b.Property<int?>("DovizId")
                        .HasColumnType("int");

                    b.Property<int?>("EvrakTur")
                        .HasColumnType("int");

                    b.Property<string>("FaturaNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FaturaTur")
                        .HasColumnType("int");

                    b.Property<DateTime>("GuncellemeTarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("GuncelleyenKullanici")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("OlusturanKullanici")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OlusturmaTarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProjeNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<long?>("WolvoxBlKodu")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("WolvoxDolarTutar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("WolvoxDovizBirimTutar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("WolvoxFaturaTutar")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.HasIndex("CariId");

                    b.HasIndex("DovizId");

                    b.ToTable("Fatura");
                });

            modelBuilder.Entity("GlobalTradeSevkiyatTakip.Domain.Entities.FaturaDetay", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("DovizId")
                        .HasColumnType("int");

                    b.Property<int?>("FaturaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("GuncellemeTarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("GuncelleyenKullanici")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HizmetId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Miktar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("OlusturanKullanici")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OlusturmaTarih")
                        .HasColumnType("datetime2");

                    b.Property<int?>("StokId")
                        .HasColumnType("int");

                    b.Property<decimal?>("ToplamTutar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("WolvoxBlKodu")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("DovizId");

                    b.HasIndex("FaturaId");

                    b.HasIndex("HizmetId");

                    b.HasIndex("StokId");

                    b.ToTable("FaturaDetay");
                });

            modelBuilder.Entity("GlobalTradeSevkiyatTakip.Domain.Entities.Hizmet", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("GuncellemeTarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("GuncelleyenKullanici")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HizmetAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("OlusturanKullanici")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OlusturmaTarih")
                        .HasColumnType("datetime2");

                    b.Property<long?>("WolvoxBlKodu")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.ToTable("Hizmet");
                });

            modelBuilder.Entity("GlobalTradeSevkiyatTakip.Domain.Entities.Irsaliye", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("CariId")
                        .HasColumnType("int");

                    b.Property<int?>("DovizId")
                        .HasColumnType("int");

                    b.Property<int?>("EvrakTur")
                        .HasColumnType("int");

                    b.Property<int?>("FaturaDurum")
                        .HasColumnType("int");

                    b.Property<DateTime>("GuncellemeTarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("GuncelleyenKullanici")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IrsaliyeNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("IrsaliyeTarih")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IrsaliyeTur")
                        .HasColumnType("int");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("OlusturanKullanici")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OlusturmaTarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProjeNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SevkAdres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SevkDurum")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SevkTarih")
                        .HasColumnType("datetime2");

                    b.Property<long?>("WolvoxBlKodu")
                        .HasColumnType("bigint");

                    b.Property<int?>("WolvoxGonderimDurum")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CariId");

                    b.HasIndex("DovizId");

                    b.ToTable("Irsaliye");
                });

            modelBuilder.Entity("GlobalTradeSevkiyatTakip.Domain.Entities.IrsaliyeDetay", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("DepoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("GuncellemeTarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("GuncelleyenKullanici")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HizmetId")
                        .HasColumnType("int");

                    b.Property<string>("Icindekiler")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IrsaliyeId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("KapAdet")
                        .HasColumnType("int");

                    b.Property<string>("KapNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Miktar")
                        .HasColumnType("int");

                    b.Property<string>("Olculer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OlusturanKullanici")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OlusturmaTarih")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PaketIciAdet")
                        .HasColumnType("int");

                    b.Property<string>("PaketSekil")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StokId")
                        .HasColumnType("int");

                    b.Property<bool?>("TakimDurum")
                        .HasColumnType("bit");

                    b.Property<string>("TedarikFirma")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ToplamKapAdet")
                        .HasColumnType("int");

                    b.Property<int?>("ToplamPaketIciAdet")
                        .HasColumnType("int");

                    b.Property<decimal?>("UrunBurutAgirlik")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UrunIcerik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("UrunNetAgirlik")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("WolvoxBlKodu")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("DepoId");

                    b.HasIndex("HizmetId");

                    b.HasIndex("IrsaliyeId");

                    b.HasIndex("StokId");

                    b.ToTable("IrsaliyeDetay");
                });

            modelBuilder.Entity("GlobalTradeSevkiyatTakip.Domain.Entities.Kullanici", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Ad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("GuncellemeTarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("GuncelleyenKullanici")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("OlusturanKullanici")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OlusturmaTarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("Parola")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Rol")
                        .HasColumnType("int");

                    b.Property<string>("Soyad")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Kullanici");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Ad = "default",
                            Email = "default@gmail.com",
                            GuncellemeTarih = new DateTime(2023, 9, 8, 16, 13, 54, 99, DateTimeKind.Local).AddTicks(2446),
                            GuncelleyenKullanici = "asd",
                            IsDeleted = false,
                            OlusturanKullanici = "sd",
                            OlusturmaTarih = new DateTime(2023, 9, 8, 16, 13, 54, 99, DateTimeKind.Local).AddTicks(2474),
                            Parola = "jyBAdWogYwoYrNvTdwxwLKavHQiYqszX7dUAggFIfZhdDQFBvLfU1q3UMnCe1yVo",
                            Rol = 2,
                            Soyad = "default"
                        });
                });

            modelBuilder.Entity("GlobalTradeSevkiyatTakip.Domain.Entities.Marka", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("GuncellemeTarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("GuncelleyenKullanici")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MarkaAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OlusturanKullanici")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OlusturmaTarih")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Marka");
                });

            modelBuilder.Entity("GlobalTradeSevkiyatTakip.Domain.Entities.ParaBirim", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("BirimSimge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("GuncellemeTarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("GuncelleyenKullanici")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("OlusturanKullanici")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OlusturmaTarih")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("ParaBirim");
                });

            modelBuilder.Entity("GlobalTradeSevkiyatTakip.Domain.Entities.Renk", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("GuncellemeTarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("GuncelleyenKullanici")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("OlusturanKullanici")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OlusturmaTarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("RenkAdi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Renk");
                });

            modelBuilder.Entity("GlobalTradeSevkiyatTakip.Domain.Entities.Sevkiyat", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("AracPlaka")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("GuncellemeTarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("GuncelleyenKullanici")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Kar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("NetMaliyet")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("OlusturanKullanici")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OlusturmaTarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProjeNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SevkiyatAdres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SevkiyatTarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoforAdSoyad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Zarar")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.ToTable("Sevkiyat");
                });

            modelBuilder.Entity("GlobalTradeSevkiyatTakip.Domain.Entities.SevkiyatDetay", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("FaturaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("GuncellemeTarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("GuncelleyenKullanici")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IrsaliyeId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("OlusturanKullanici")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OlusturmaTarih")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SevkiyatId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("FaturaId");

                    b.HasIndex("IrsaliyeId");

                    b.HasIndex("SevkiyatId");

                    b.ToTable("SevkiyatDetay");
                });

            modelBuilder.Entity("GlobalTradeSevkiyatTakip.Domain.Entities.SevkiyatNot", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("GuncellemeTarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("GuncelleyenKullanici")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<string>("Metin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OlusturanKullanici")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OlusturmaTarih")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("KullaniciId");

                    b.ToTable("SevkiyatNot");
                });

            modelBuilder.Entity("GlobalTradeSevkiyatTakip.Domain.Entities.Stok", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal?>("Agirlik")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Barkod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DepoId")
                        .HasColumnType("int");

                    b.Property<decimal?>("DesiMiktari")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DovizBirim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("GuncellemeTarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("GuncelleyenKullanici")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("IskontoOran")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KdvOran")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MarkaId")
                        .HasColumnType("int");

                    b.Property<string>("OlusturanKullanici")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OlusturmaTarih")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RenkId")
                        .HasColumnType("int");

                    b.Property<string>("StokAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StokKod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("WolvoxBlKodu")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("DepoId");

                    b.HasIndex("MarkaId");

                    b.HasIndex("RenkId");

                    b.ToTable("Stok");
                });

            modelBuilder.Entity("GlobalTradeSevkiyatTakip.Domain.Entities.StokDetay", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("CariId")
                        .HasColumnType("int");

                    b.Property<decimal?>("CikisMiktar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("DepoId")
                        .HasColumnType("int");

                    b.Property<decimal?>("GirisMiktar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("GuncellemeTarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("GuncelleyenKullanici")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal?>("NetMiktar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("OlusturanKullanici")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OlusturmaTarih")
                        .HasColumnType("datetime2");

                    b.Property<int?>("StokId")
                        .HasColumnType("int");

                    b.Property<long?>("WolvoxBlKodu")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("CariId");

                    b.HasIndex("DepoId");

                    b.HasIndex("StokId");

                    b.ToTable("StokDetay");
                });

            modelBuilder.Entity("GlobalTradeSevkiyatTakip.Domain.Entities.DepoDetay", b =>
                {
                    b.HasOne("GlobalTradeSevkiyatTakip.Domain.Entities.Cari", "Cari")
                        .WithMany()
                        .HasForeignKey("CariId");

                    b.HasOne("GlobalTradeSevkiyatTakip.Domain.Entities.Depo", "Depo")
                        .WithMany("Detay")
                        .HasForeignKey("DepoId");

                    b.HasOne("GlobalTradeSevkiyatTakip.Domain.Entities.Stok", "Stok")
                        .WithMany()
                        .HasForeignKey("StokId");

                    b.Navigation("Cari");

                    b.Navigation("Depo");

                    b.Navigation("Stok");
                });

            modelBuilder.Entity("GlobalTradeSevkiyatTakip.Domain.Entities.Fatura", b =>
                {
                    b.HasOne("GlobalTradeSevkiyatTakip.Domain.Entities.Cari", "Cari")
                        .WithMany()
                        .HasForeignKey("CariId");

                    b.HasOne("GlobalTradeSevkiyatTakip.Domain.Entities.Doviz", "Doviz")
                        .WithMany()
                        .HasForeignKey("DovizId");

                    b.Navigation("Cari");

                    b.Navigation("Doviz");
                });

            modelBuilder.Entity("GlobalTradeSevkiyatTakip.Domain.Entities.FaturaDetay", b =>
                {
                    b.HasOne("GlobalTradeSevkiyatTakip.Domain.Entities.Doviz", "Doviz")
                        .WithMany()
                        .HasForeignKey("DovizId");

                    b.HasOne("GlobalTradeSevkiyatTakip.Domain.Entities.Fatura", "Fatura")
                        .WithMany("Detay")
                        .HasForeignKey("FaturaId");

                    b.HasOne("GlobalTradeSevkiyatTakip.Domain.Entities.Hizmet", "Hizmet")
                        .WithMany()
                        .HasForeignKey("HizmetId");

                    b.HasOne("GlobalTradeSevkiyatTakip.Domain.Entities.Stok", "Stok")
                        .WithMany()
                        .HasForeignKey("StokId");

                    b.Navigation("Doviz");

                    b.Navigation("Fatura");

                    b.Navigation("Hizmet");

                    b.Navigation("Stok");
                });

            modelBuilder.Entity("GlobalTradeSevkiyatTakip.Domain.Entities.Irsaliye", b =>
                {
                    b.HasOne("GlobalTradeSevkiyatTakip.Domain.Entities.Cari", "Cari")
                        .WithMany()
                        .HasForeignKey("CariId");

                    b.HasOne("GlobalTradeSevkiyatTakip.Domain.Entities.Doviz", "Doviz")
                        .WithMany()
                        .HasForeignKey("DovizId");

                    b.Navigation("Cari");

                    b.Navigation("Doviz");
                });

            modelBuilder.Entity("GlobalTradeSevkiyatTakip.Domain.Entities.IrsaliyeDetay", b =>
                {
                    b.HasOne("GlobalTradeSevkiyatTakip.Domain.Entities.Depo", "Depo")
                        .WithMany()
                        .HasForeignKey("DepoId");

                    b.HasOne("GlobalTradeSevkiyatTakip.Domain.Entities.Hizmet", "Hizmet")
                        .WithMany()
                        .HasForeignKey("HizmetId");

                    b.HasOne("GlobalTradeSevkiyatTakip.Domain.Entities.Irsaliye", "Irsaliye")
                        .WithMany("IrsaliyeDetay")
                        .HasForeignKey("IrsaliyeId");

                    b.HasOne("GlobalTradeSevkiyatTakip.Domain.Entities.Stok", "Stok")
                        .WithMany()
                        .HasForeignKey("StokId");

                    b.Navigation("Depo");

                    b.Navigation("Hizmet");

                    b.Navigation("Irsaliye");

                    b.Navigation("Stok");
                });

            modelBuilder.Entity("GlobalTradeSevkiyatTakip.Domain.Entities.SevkiyatDetay", b =>
                {
                    b.HasOne("GlobalTradeSevkiyatTakip.Domain.Entities.Fatura", "Fatura")
                        .WithMany()
                        .HasForeignKey("FaturaId");

                    b.HasOne("GlobalTradeSevkiyatTakip.Domain.Entities.Irsaliye", "Irsaliye")
                        .WithMany()
                        .HasForeignKey("IrsaliyeId");

                    b.HasOne("GlobalTradeSevkiyatTakip.Domain.Entities.Sevkiyat", "Sevkiyat")
                        .WithMany("SevkiyatDetay")
                        .HasForeignKey("SevkiyatId");

                    b.Navigation("Fatura");

                    b.Navigation("Irsaliye");

                    b.Navigation("Sevkiyat");
                });

            modelBuilder.Entity("GlobalTradeSevkiyatTakip.Domain.Entities.SevkiyatNot", b =>
                {
                    b.HasOne("GlobalTradeSevkiyatTakip.Domain.Entities.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("GlobalTradeSevkiyatTakip.Domain.Entities.Stok", b =>
                {
                    b.HasOne("GlobalTradeSevkiyatTakip.Domain.Entities.Depo", "Depo")
                        .WithMany()
                        .HasForeignKey("DepoId");

                    b.HasOne("GlobalTradeSevkiyatTakip.Domain.Entities.Marka", "Marka")
                        .WithMany()
                        .HasForeignKey("MarkaId");

                    b.HasOne("GlobalTradeSevkiyatTakip.Domain.Entities.Renk", "Renk")
                        .WithMany()
                        .HasForeignKey("RenkId");

                    b.Navigation("Depo");

                    b.Navigation("Marka");

                    b.Navigation("Renk");
                });

            modelBuilder.Entity("GlobalTradeSevkiyatTakip.Domain.Entities.StokDetay", b =>
                {
                    b.HasOne("GlobalTradeSevkiyatTakip.Domain.Entities.Cari", "Cari")
                        .WithMany()
                        .HasForeignKey("CariId");

                    b.HasOne("GlobalTradeSevkiyatTakip.Domain.Entities.Depo", "Depo")
                        .WithMany()
                        .HasForeignKey("DepoId");

                    b.HasOne("GlobalTradeSevkiyatTakip.Domain.Entities.Stok", "Stok")
                        .WithMany()
                        .HasForeignKey("StokId");

                    b.Navigation("Cari");

                    b.Navigation("Depo");

                    b.Navigation("Stok");
                });

            modelBuilder.Entity("GlobalTradeSevkiyatTakip.Domain.Entities.Depo", b =>
                {
                    b.Navigation("Detay");
                });

            modelBuilder.Entity("GlobalTradeSevkiyatTakip.Domain.Entities.Fatura", b =>
                {
                    b.Navigation("Detay");
                });

            modelBuilder.Entity("GlobalTradeSevkiyatTakip.Domain.Entities.Irsaliye", b =>
                {
                    b.Navigation("IrsaliyeDetay");
                });

            modelBuilder.Entity("GlobalTradeSevkiyatTakip.Domain.Entities.Sevkiyat", b =>
                {
                    b.Navigation("SevkiyatDetay");
                });
#pragma warning restore 612, 618
        }
    }
}
